"""
C语言头文件生成器
从SVD数据生成C语言头文件，供固件开发使用
"""
import os
import logging
from typing import Optional


class HeaderGenerator:
    """C语言头文件生成器"""

    def __init__(self, device_info):
        self.device_info = device_info
        self.logger = logging.getLogger("HeaderGenerator")

    def generate(self, style: str = "upper_case", prefix: str = "") -> str:
        """生成C头文件内容

        Args:
            style: 命名风格 (upper_case, camel_case)
            prefix: 自定义前缀

        Returns:
            C头文件内容字符串
        """
        device = self.device_info
        device_name = self._safe_name(device.name or "DEVICE")
        guard = f"__{device_name}_H__"

        lines = []
        lines.append(f"#ifndef {guard}")
        lines.append(f"#define {guard}")
        lines.append("")
        lines.append(f"/*")
        lines.append(f" * Device: {device.name or 'Unknown'}")
        lines.append(f" * Vendor: {device.vendor or 'Unknown'}")
        lines.append(f" * Version: {device.version or '1.0'}")
        lines.append(f" * Generated by SVDEditor")
        lines.append(f" */")
        lines.append("")
        lines.append('#include <stdint.h>')
        lines.append("")

        # 生成设备基地址宏
        lines.append("/* ========== Device Base Addresses ========== */")
        for periph_name, periph in device.peripherals.items():
            safe = self._format_name(periph_name, style, prefix)
            base_addr = periph.base_address or 0
            if isinstance(base_addr, str):
                base_addr = int(base_addr, 0)
            lines.append(f"#define {safe}_BASE    ((uint32_t)0x{base_addr:08X}UL)")
        lines.append("")

        # 生成外设寄存器结构体
        lines.append("/* ========== Peripheral Register Structures ========== */")
        for periph_name, periph in device.peripherals.items():
            safe = self._format_name(periph_name, style, prefix)
            lines.append(f"/* {periph.description or periph_name} */")
            lines.append(f"typedef struct {{")
            lines.append(f"    __IO uint32_t RESERVED0; /* Placeholder - see register offsets */")

            # 生成寄存器偏移宏
            for reg_name, reg in periph.registers.items():
                reg_safe = self._format_name(reg_name, style, prefix)
                offset = reg.offset
                if isinstance(offset, str):
                    offset = int(offset, 0)
                lines.append(f"    /* {reg.description or reg_name} (offset: 0x{offset:02X}) */")
                lines.append(f"    __IO uint32_t {reg_safe};")

            lines.append(f"}} {safe}_TypeDef;")
            lines.append(f"#define {safe}  (({safe}_TypeDef *) {safe}_BASE)")
            lines.append("")

        # 生成位域宏
        lines.append("/* ========== Register Bit Field Macros ========== */")
        for periph_name, periph in device.peripherals.items():
            for reg_name, reg in periph.registers.items():
                if not reg.fields:
                    continue
                reg_safe = self._format_name(reg_name, style, prefix)
                periph_safe = self._format_name(periph_name, style, prefix)
                lines.append(f"/* {periph_name}.{reg_name} bit fields */")
                for field_name, field in reg.fields.items():
                    f_safe = self._format_name(field_name, style, prefix)
                    bit_offset = field.bit_offset or 0
                    bit_width = field.bit_width or 1
                    mask = ((1 << bit_width) - 1) << bit_offset
                    lines.append(f"#define {periph_safe}_{reg_safe}_{f_safe}_POS    ({bit_offset}U)")
                    lines.append(f"#define {periph_safe}_{reg_safe}_{f_safe}_MSK    (0x{mask:08X}U)")
                    lines.append(f"#define {periph_safe}_{reg_safe}_{f_safe}        ((uint32_t)0x{mask:08X}U)")
                lines.append("")

        # 生成中断号枚举
        if device.interrupts:
            lines.append("/* ========== Interrupt Numbers ========== */")
            lines.append(f"typedef enum {{")
            sorted_irqs = sorted(device.interrupts.values(), key=lambda x: x.value)
            for irq in sorted_irqs:
                irq_safe = self._format_name(irq.name, style, prefix)
                lines.append(f"    {irq_safe}_IRQn = {irq.value},")
            lines.append(f"}} {self._format_name(device_name, style, prefix)}_IRQn_TypeDef;")
            lines.append("")

        lines.append(f"#endif /* {guard} */")
        lines.append("")
        return "\n".join(lines)

    def _safe_name(self, name: str) -> str:
        """将名称转为安全的C标识符"""
        safe = name.replace(" ", "_").replace("-", "_").replace(".", "_")
        # 移除非字母数字字符
        result = ""
        for ch in safe:
            if ch.isalnum() or ch == "_":
                result += ch
        if result and result[0].isdigit():
            result = "_" + result
        return result or "UNKNOWN"

    def _format_name(self, name: str, style: str, prefix: str = "") -> str:
        """格式化名称"""
        safe = self._safe_name(name)
        if style == "upper_case":
            safe = safe.upper()
        elif style == "camel_case":
            parts = safe.split("_")
            safe = parts[0].lower() + "".join(p.capitalize() for p in parts[1:])

        if prefix:
            safe = prefix + safe
        return safe

    def save_to_file(self, file_path: str, style: str = "upper_case", prefix: str = "") -> bool:
        """生成头文件并保存到文件"""
        try:
            content = self.generate(style=style, prefix=prefix)
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            self.logger.info(f"头文件已保存到: {file_path}")
            return True
        except Exception as e:
            self.logger.error(f"保存头文件失败: {e}")
            return False